### ISSUE TITLE
Default System segment message expiry not respected

### ISSUE THREAD

**Issue by FireMasterK** [iggy-rs/iggy#1536]
I'm running iggy like this in docker-compose:
```
  iggy-server:
    image: iggyrs/iggy:0.4.203
    container_name: iggy-server
    ports:
      - "127.0.0.1:8090:8090"
      - "100.107.7.89:8090:8090"
      - "127.0.0.1:3000:3000"
    environment:
      IGGY_SYSTEM_MESSAGE_DEDUPLICATION_ENABLED: "true"
      IGGY_SYSTEM_CACHE_SIZE: "512MB"
      IGGY_SYSTEM_SEGMENT_MESSAGE_EXPIRY: "5m"
      IGGY_DATA_MAINTENANCE_MESSAGES_CLEANER_ENABLED: "true"
      IGGY_SYSTEM_CACHE_ENABLED: "false"
    restart: unless-stopped
    volumes:
      - iggy-server:/iggy/local_data
```

When I run these:
```
docker exec -it iggy-server iggy --username iggy --password iggy stream create exchange-data
docker exec -it iggy-server iggy --username iggy --password iggy topic create exchange-data stocks-prices 1 none
```

The message expiry is still unlimited:
```
docker exec -it iggy-server iggy --username iggy --password iggy topic l 1
```
