### ISSUE TITLE
Document server.toml

### ISSUE THREAD

**Issue by hubcio** [iggy-rs/iggy#260]
Something like this, in the toml file itself:
```toml
# HTTP server configuration
[http]
# Whether the HTTP server is enabled (boolean)
# `true` to enable the server, `false` to disable it.
enabled = true

# The socket address where the server will be accessible (string)
# Format: "HOST:PORT". "0.0.0.0" binds to all host IPs.
address = "0.0.0.0:3000"

# Cross-Origin Resource Sharing (CORS) settings
# This section defines the CORS policy for the HTTP server.
[http.cors]
# Whether CORS support is enabled (boolean)
# `true` enables CORS, `false` disables it.
enabled = true
```
