### ISSUE TITLE
Why is Quic so much slower (half the tcp msg/sec)?

### ISSUE THREAD

**Issue by marvin-hansen** [iggy-rs/iggy#606]
Hi,

I ran the benchmark today and I got the following numbers:

TCP:
Results: total throughput: 
402.47 MB/s, 
10061816 messages/s, 
average latency: 0.99 ms, 
average  throughput: 40.25 MB/s, 
total duration: 0.99 s

HTTP:
 Results: total throughput: 
344.18 MB/s, 
8604598 messages/s, 
average latency: 1.16 ms, 
average  throughput: 34.42 MB/s, 
total duration: 1.16 s

QUIC:
 Results: total throughput: 
202.72 MB/s, 
5068119 messages/s, 
average latency: 1.97 ms, 
average  throughput: 20.27 MB/s, 
total duration: 1.97 s

Command:

```bash
RUSTFLAGS='-C target-cpu=native' cargo r --bin iggy-bench -r -- -c -v send --message-size 40 tcp 
```

A few more details:
* My max message size is 40 bytes (SBE Encoded)
* The cpu=native flag usually gives a notch better optimized code

I understand that QUIC is build on top of UDP, but afaik, UDP messaging is usually faster than TCP
because of lower protocol overhead, so it's baffling to see QUIC being only half as fast and 
I wonder if there is any particular reason for that?

Also, it seems that Iggy maxes out at about 20million msg/sec on my box
using the following benchmark:

```bash
RUSTFLAGS='-C target-cpu=native' cargo r --bin iggy-bench -r -- -c -v send-and-poll  --message-size 40 tcp 
```

And the following entry in the Cargo.toml 
```toml
# Optimize all crates
[profile.release]
opt-level = 3
strip = true  # Automatically strip debug symbols from the binary
lto = true    # Enable Link Time Optimization (LTO)
codegen-units = 1 # Reduce Parallel Code Generation Units to Increase Optimization

# There's a Cargo feature named profile-overrides
# that lets you override the optimization level of dependencies.
# https://docs.rust-embedded.org/book/unsorted/speed-vs-size.html
[profile.release.package."*"]
opt-level = 3
strip = true  
codegen-units = 1 
```

20 million msg/sec via tcp is pretty nuts and already blows several commercial systems out of the water.

By your experience, how close is production throughput to the benchmark results?
